### ISSUE TITLE
Show precise exp value of encounter

### ISSUE THREAD

**Issue by Jocarnail** [maxiride/pf-encounters#6]
The bar at the top doesn't show clearly the amount of exp budget in use. There is no scale and the threshold cover a wide amount of bar, making it difficult to see if the budget is the correct one.
I suggest the reduction in horizontal size of the bar and addition of a numeric output in the freed-up space.

**Comment by maxiride** [comment]
Fixed with  289f640

Furthermore, the threat levels are now correctly positioned along the progress bar so correctly match total encounter cost.
